# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/STUDY/Hardware implementation of CRYSTALS-Dlithium/Kyber/code/Vivado/wrapKyber/wrapKyber.srcs/sources_1/ip/MULT6/MULT6.xci
# IP: The module: 'MULT6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/STUDY/Hardware implementation of CRYSTALS-Dlithium/Kyber/code/Vivado/wrapKyber/wrapKyber.gen/sources_1/ip/MULT6/MULT6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MULT6'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/STUDY/Hardware implementation of CRYSTALS-Dlithium/Kyber/code/Vivado/wrapKyber/wrapKyber.srcs/sources_1/ip/MULT6/MULT6.xci
# IP: The module: 'MULT6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/STUDY/Hardware implementation of CRYSTALS-Dlithium/Kyber/code/Vivado/wrapKyber/wrapKyber.gen/sources_1/ip/MULT6/MULT6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MULT6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
