# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/STUDY/Hardware implementation of CRYSTALS-Dlithium/Kyber/code/BU/BU.srcs/sources_1/ip/MULT3/MULT3.xci
# IP: The module: 'MULT3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/STUDY/Hardware implementation of CRYSTALS-Dlithium/Kyber/code/BU/BU.gen/sources_1/ip/MULT3/MULT3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MULT3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/STUDY/Hardware implementation of CRYSTALS-Dlithium/Kyber/code/BU/BU.srcs/sources_1/ip/MULT3/MULT3.xci
# IP: The module: 'MULT3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/STUDY/Hardware implementation of CRYSTALS-Dlithium/Kyber/code/BU/BU.gen/sources_1/ip/MULT3/MULT3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MULT3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
