# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/302.xdc

# IP: ip/MULT6/MULT6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MULT6 || ORIG_REF_NAME==MULT6} -quiet] -quiet

# IP: ip/MULT3/MULT3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MULT3 || ORIG_REF_NAME==MULT3} -quiet] -quiet
